#!/bin/bash

# Prompt the user for input
input_text=/home/$USER/My-Banner/abdullah

# Prompt the user for the file location
file_location=/home/$USER/.zshrc

# Check if the file exists, if not, create it
if [ ! -f "$file_location" ]; then
    touch "$file_location"
fi

# Append the input text to the file
echo "$input_text" >> "$file_location"

# Notify the user
echo "Text has been written to $file_location"
